-- egumball_db.mapwordsproposals definition

CREATE TABLE `mapwordsproposals` (
  `id` int NOT NULL,
  `whenadded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `companyname` varchar(250) DEFAULT NULL,
  `address` varchar(250) DEFAULT NULL,
  `city` varchar(250) DEFAULT NULL,
  `state` varchar(250) DEFAULT NULL,
  `zip` varchar(50) DEFAULT NULL,
  `web` varchar(250) DEFAULT NULL,
  `email` varchar(250) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `fax` varchar(50) DEFAULT NULL,
  `tollphone` varchar(50) DEFAULT NULL,
  `mobilephone` varchar(50) DEFAULT NULL,
  `rep` varchar(45) DEFAULT NULL,
  `yearest` varchar(5) DEFAULT NULL,
  `k1` varchar(100) DEFAULT NULL,
  `k2` varchar(100) DEFAULT NULL,
  `k3` varchar(100) DEFAULT NULL,
  `k4` varchar(100) DEFAULT NULL,
  `k5` varchar(100) DEFAULT NULL,
  `k6` varchar(100) DEFAULT NULL,
  `k7` varchar(100) DEFAULT NULL,
  `k8` varchar(100) DEFAULT NULL,
  `k9` varchar(100) DEFAULT NULL,
  `k10` varchar(100) DEFAULT NULL,
  `as1` varchar(100) DEFAULT NULL,
  `as2` varchar(100) DEFAULT NULL,
  `as3` varchar(100) DEFAULT NULL,
  `as4` varchar(100) DEFAULT NULL,
  `as5` varchar(100) DEFAULT NULL,
  `setup` varchar(45) DEFAULT NULL,
  `installment` varchar(45) DEFAULT NULL,
  `contactname` varchar(100) DEFAULT NULL,
  `creditcard` varchar(45) DEFAULT NULL,
  `expmo` varchar(5) DEFAULT NULL,
  `expyr` varchar(5) DEFAULT NULL,
  `chkno` varchar(10) DEFAULT NULL,
  `rtno` varchar(45) DEFAULT NULL,
  `acctno` varchar(45) DEFAULT NULL,
  `term` varchar(10) DEFAULT NULL,
  `pincode` varchar(45) DEFAULT NULL,
  `cash` tinyint(1) DEFAULT NULL,
  `chks` tinyint(1) DEFAULT NULL,
  `amex` tinyint(1) DEFAULT NULL,
  `mastercard` tinyint(1) DEFAULT NULL,
  `visa` tinyint(1) DEFAULT NULL,
  `discover` tinyint(1) DEFAULT NULL,
  `westernunion` tinyint(1) DEFAULT NULL,
  `paypal` tinyint(1) DEFAULT NULL,
  `wires` tinyint(1) DEFAULT NULL,
  `travelers_checks` tinyint(1) DEFAULT '0',
  `invoice` tinyint(1) DEFAULT '0',
  `diner_club` tinyint(1) DEFAULT '0',
  `open24_7` tinyint(1) DEFAULT '0',
  `sun_open` datetime DEFAULT NULL,
  `sun_close` datetime DEFAULT NULL,
  `mon_open` datetime DEFAULT NULL,
  `mon_close` datetime DEFAULT NULL,
  `tue_open` datetime DEFAULT NULL,
  `tue_close` datetime DEFAULT NULL,
  `wed_open` datetime DEFAULT NULL,
  `wed_close` datetime DEFAULT NULL,
  `thur_open` datetime DEFAULT NULL,
  `thur_close` datetime DEFAULT NULL,
  `fri_open` datetime DEFAULT NULL,
  `fri_close` datetime DEFAULT NULL,
  `sat_open` datetime DEFAULT NULL,
  `sat_close` datetime DEFAULT NULL,
  `sun_is_working_hours` tinyint(1) DEFAULT '1',
  `mon_is_working_hours` tinyint(1) DEFAULT '1',
  `tue_is_working_hours` tinyint(1) DEFAULT '1',
  `wed_is_working_hours` tinyint(1) DEFAULT '1',
  `thur_is_working_hours` tinyint(1) DEFAULT '1',
  `fri_is_working_hours` tinyint(1) DEFAULT '1',
  `sat_is_working_hours` tinyint(1) DEFAULT '1',
  `cat_1` varchar(100) DEFAULT NULL,
  `cat_2` varchar(100) DEFAULT NULL,
  `cat_3` varchar(100) DEFAULT NULL,
  `bizdescription` longtext,
  `facebook` varchar(100) DEFAULT NULL,
  `twitter` varchar(100) DEFAULT NULL,
  `youtube` varchar(100) DEFAULT NULL,
  `instagram` varchar(100) DEFAULT NULL,
  `datademo` tinyint(1) DEFAULT NULL,
  `pid` bigint DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `placeid` varchar(300) DEFAULT NULL,
  `pincodeCreated` datetime DEFAULT NULL,
  `pkg` varchar(50) DEFAULT NULL,
  `price` decimal(15,2) DEFAULT NULL,
  `token` text,
  `business_email` varchar(255) DEFAULT NULL,
  `Key1Contact` longtext,
  `Key1ContactDesc` longtext,
  `Key2Contact` longtext,
  `Key2ContactDesc` longtext,
  `Key3Contact` longtext,
  `Key3ContactDesc` longtext,
  `Key4Contact` longtext,
  `Key4ContactDesc` longtext,
  `Key5Contact` longtext,
  `Key5ContactDesc` longtext,
  `AboutUs` longtext,
  `MissionStatement` longtext,
  `Disclosure` longtext,
  `ServCity1` longtext,
  `ServCity2` longtext,
  `ServCity3` longtext,
  `ServCity4` longtext,
  `ServCity5` longtext,
  `ServCity6` longtext,
  `ServCity7` longtext,
  `ServCity8` longtext,
  `ServCity9` longtext,
  `ServCity10` longtext,
  `ServCity11` longtext,
  `ServCity12` longtext,
  `ServCity13` longtext,
  `ServCity14` longtext,
  `ServCity15` longtext,
  `cat_4` longtext,
  `cat_5` longtext,
  `Zip_Serv1` varchar(10) DEFAULT NULL,
  `Zip_Serv2` varchar(10) DEFAULT NULL,
  `Zip_Serv3` varchar(10) DEFAULT NULL,
  `Zip_Serv4` varchar(10) DEFAULT NULL,
  `Zip_Serv5` varchar(10) DEFAULT NULL,
  `Zip_Serv6` varchar(10) DEFAULT NULL,
  `Zip_Serv7` varchar(10) DEFAULT NULL,
  `Zip_Serv8` varchar(10) DEFAULT NULL,
  `Zip_Serv9` varchar(10) DEFAULT NULL,
  `Zip_Serv10` varchar(10) DEFAULT NULL,
  `Zip_Serv11` varchar(10) DEFAULT NULL,
  `Zip_Serv12` varchar(10) DEFAULT NULL,
  `Zip_Serv13` varchar(10) DEFAULT NULL,
  `Zip_Serv14` varchar(10) DEFAULT NULL,
  `Zip_Serv15` varchar(10) DEFAULT NULL,
  `facebook_user_id` varchar(250) DEFAULT NULL,
  `gmail_user_id` varchar(250) DEFAULT NULL,
  `DoNotShowPictures` tinyint(1) NOT NULL,
  `DoNotShowVideo` tinyint(1) NOT NULL,
  `DoNotShowMap` tinyint(1) NOT NULL,
  `DoNotShowNavigationPhoneNumber` tinyint(1) NOT NULL,
  `DoNotShowHours` tinyint(1) NOT NULL,
  `DoNotShowReviews` tinyint(1) NOT NULL,
  `DoNotShowCoupons` tinyint(1) NOT NULL,
  `DoNotShowAddress` tinyint(1) NOT NULL,
  `installment_period` int DEFAULT '1',
  `installment_period_option` int DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- egumball_db.`order` definition

CREATE TABLE `order` (
  `id` varchar(255) NOT NULL,
  `createdAt` datetime DEFAULT NULL,
  `pkg` varchar(50) DEFAULT NULL,
  `payment_amount` varchar(50) DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `demo_user` tinyint(1) DEFAULT '0',
  `purchased_quantity` int DEFAULT NULL,
  `payment_duration_option` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- egumball_db.billing definition

CREATE TABLE `billing` (
  `id` varchar(36) NOT NULL,
  `card_number` varchar(255) DEFAULT NULL,
  `card_holder_name` varchar(255) DEFAULT NULL,
  `expiration_date` varchar(255) DEFAULT NULL,
  `cvv` varchar(255) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `createdAt` timestamp NULL DEFAULT NULL,
  `modifiedAt` timestamp NULL DEFAULT NULL,
  `payment_method` varchar(30) DEFAULT NULL,
  `payment_amount` varchar(10) DEFAULT NULL,
  `purchased_quantity` int DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `billing_address` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(100) DEFAULT NULL,
  `zip_code` varchar(20) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `status` varchar(30) DEFAULT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `package` varchar(30) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `bank_name` varchar(255) DEFAULT NULL,
  `bank_routing` varchar(255) DEFAULT NULL,
  `account_number` varchar(255) DEFAULT NULL,
  `payment_duration_option` varchar(50) DEFAULT NULL,
  `demo_user` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- egumball_db.clients definition

CREATE TABLE `clients` (
  `ProfileID` int DEFAULT NULL,
  `EMail` varchar(255) DEFAULT NULL,
  `pwd` varchar(50) DEFAULT NULL,
  `name` varchar(110) DEFAULT NULL,
  `FirstName` varchar(50) DEFAULT NULL,
  `LastName` varchar(50) DEFAULT NULL,
  `whenRegistered` datetime DEFAULT NULL,
  `lastSignin` datetime DEFAULT NULL,
  `lastStatisticsUpdate` datetime DEFAULT NULL,
  `primaryIP` varchar(20) DEFAULT NULL,
  `secondaryIP` varchar(20) DEFAULT NULL,
  `TermsLastAcknowledged` datetime DEFAULT NULL,
  `lastSeenTools` datetime DEFAULT NULL,
  `facebookUserId` varchar(50) DEFAULT NULL,
  `ResetToken` varchar(36) DEFAULT NULL,
  `ResetTokenDeadlineMs` bigint DEFAULT NULL,
  `gmailUserId` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;


-- egumball_db.profile definition

CREATE TABLE `profile` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Client_ID` varchar(255) DEFAULT NULL,
  `CustomerSince` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Active` tinyint(1) DEFAULT '0',
  `template` varchar(30) DEFAULT NULL,
  `URL` varchar(250) DEFAULT NULL,
  `URL2` varchar(250) DEFAULT NULL,
  `URL3` varchar(250) DEFAULT NULL,
  `URL4` varchar(250) DEFAULT NULL,
  `URL5` varchar(250) DEFAULT NULL,
  `URL6` varchar(255) DEFAULT NULL,
  `URL7` varchar(255) DEFAULT NULL,
  `url8` varchar(255) DEFAULT NULL,
  `url9` varchar(255) DEFAULT NULL,
  `url10` varchar(255) DEFAULT NULL,
  `CustomURL` tinyint(1) DEFAULT '0',
  `DisplayStyle` varchar(50) DEFAULT NULL,
  `Contract` varchar(50) DEFAULT NULL,
  `YouTubeCat` varchar(255) DEFAULT NULL,
  `BusinessType` varchar(250) DEFAULT NULL,
  `NetworkPath` varchar(250) DEFAULT NULL,
  `InActive` tinyint(1) DEFAULT '0',
  `Company` varchar(250) DEFAULT NULL,
  `Address` varchar(250) DEFAULT NULL,
  `City` varchar(250) DEFAULT NULL,
  `St` varchar(250) DEFAULT NULL,
  `Zip` varchar(50) DEFAULT NULL,
  `Name` varchar(250) DEFAULT NULL,
  `SpecialTitle` varchar(250) DEFAULT NULL,
  `LegalTitle` varchar(250) DEFAULT NULL,
  `Phone1` varchar(50) DEFAULT NULL,
  `TollFree` varchar(50) DEFAULT NULL,
  `Mobile` varchar(50) DEFAULT NULL,
  `Fax` varchar(50) DEFAULT NULL,
  `Email` varchar(250) DEFAULT NULL,
  `Website` varchar(250) DEFAULT NULL,
  `HttpAddress` varchar(250) DEFAULT NULL,
  `Website2` varchar(255) DEFAULT NULL,
  `HttpAddress2` varchar(255) DEFAULT NULL,
  `Directions` varchar(250) DEFAULT NULL,
  `RelevantTitle` varchar(250) DEFAULT NULL,
  `GoogleMstrCat` varchar(255) DEFAULT NULL,
  `K1` varchar(50) DEFAULT NULL,
  `K2` varchar(50) DEFAULT NULL,
  `K3` varchar(50) DEFAULT NULL,
  `K4` varchar(50) DEFAULT NULL,
  `K5` varchar(50) DEFAULT NULL,
  `K6` varchar(50) DEFAULT NULL,
  `K7` varchar(50) DEFAULT NULL,
  `K8` varchar(50) DEFAULT NULL,
  `K9` varchar(50) DEFAULT NULL,
  `K10` varchar(50) DEFAULT NULL,
  `K11` varchar(255) DEFAULT NULL,
  `K12` varchar(255) DEFAULT NULL,
  `K13` varchar(255) DEFAULT NULL,
  `K14` varchar(255) DEFAULT NULL,
  `K15` varchar(255) DEFAULT NULL,
  `K16` varchar(255) DEFAULT NULL,
  `K17` varchar(255) DEFAULT NULL,
  `K18` varchar(255) DEFAULT NULL,
  `K19` varchar(255) DEFAULT NULL,
  `K20` varchar(255) DEFAULT NULL,
  `MissionStatement` longtext,
  `MapAddress` varchar(250) DEFAULT NULL,
  `KS1` varchar(250) DEFAULT NULL,
  `KS2` varchar(250) DEFAULT NULL,
  `KS3` varchar(250) DEFAULT NULL,
  `KS4` varchar(250) DEFAULT NULL,
  `KS5` varchar(250) DEFAULT NULL,
  `KS6` varchar(250) DEFAULT NULL,
  `KS7` varchar(250) DEFAULT NULL,
  `KS8` varchar(250) DEFAULT NULL,
  `KS9` varchar(250) DEFAULT NULL,
  `KS10` varchar(250) DEFAULT NULL,
  `Services1` varchar(250) DEFAULT NULL,
  `Services2` varchar(250) DEFAULT NULL,
  `Services3` varchar(250) DEFAULT NULL,
  `Services4` varchar(250) DEFAULT NULL,
  `Services5` varchar(250) DEFAULT NULL,
  `Services6` varchar(250) DEFAULT NULL,
  `Services7` varchar(250) DEFAULT NULL,
  `Services8` varchar(250) DEFAULT NULL,
  `Services9` varchar(250) DEFAULT NULL,
  `Services10` varchar(250) DEFAULT NULL,
  `YearEst` varchar(50) DEFAULT NULL,
  `AreasServed` varchar(250) DEFAULT NULL,
  `Specialty` varchar(250) DEFAULT NULL,
  `title` varchar(250) DEFAULT NULL,
  `title2` varchar(205) DEFAULT NULL,
  `title3` varchar(250) DEFAULT NULL,
  `Price` varchar(50) DEFAULT NULL,
  `Term` varchar(100) DEFAULT NULL,
  `ResellerID` varchar(50) DEFAULT NULL,
  `Visa` tinyint(1) DEFAULT '0',
  `MasterCard` tinyint(1) DEFAULT '0',
  `Amex` tinyint(1) DEFAULT '0',
  `Discover` tinyint(1) DEFAULT '0',
  `Checks` tinyint(1) DEFAULT '0',
  `Invoice` tinyint(1) DEFAULT '0',
  `Cash` tinyint(1) DEFAULT '0',
  `Wires` tinyint(1) DEFAULT '0',
  `Diners` tinyint(1) DEFAULT '0',
  `TravelersChecks` tinyint(1) DEFAULT '0',
  `PayPal` tinyint(1) DEFAULT '0',
  `ServCity1` longtext,
  `ServCity2` longtext,
  `ServCity3` longtext,
  `ServCity4` longtext,
  `ServCity5` longtext,
  `ServCity6` longtext,
  `ServCity7` longtext,
  `ServCity8` longtext,
  `ServCity9` varchar(50) DEFAULT NULL,
  `ServCity10` longtext,
  `ServCity11` longtext,
  `ServCity12` longtext,
  `ServCity13` longtext,
  `ServCity14` longtext,
  `ServCity15` longtext,
  `24HourPhone` longtext,
  `Boost` tinyint(1) DEFAULT '0',
  `BoostDate` datetime DEFAULT NULL,
  `Article` longtext,
  `Tag1` longtext,
  `Tag2` longtext,
  `Tag3` longtext,
  `Tag4` longtext,
  `Tag5` longtext,
  `Tag6` longtext,
  `Tag7` longtext,
  `Tag8` longtext,
  `Tag9` longtext,
  `Tag10` longtext,
  `Phone24` varchar(15) DEFAULT NULL,
  `Key1Contact` longtext,
  `Key1ContactDesc` longtext,
  `Key2Contact` longtext,
  `Key2ContactDesc` longtext,
  `Key3Contact` longtext,
  `Key3ContactDesc` longtext,
  `Key4Contact` longtext,
  `Key4ContactDesc` longtext,
  `Key5Contact` longtext,
  `Key5ContactDesc` longtext,
  `DoNotShowHours` tinyint(1) DEFAULT '0',
  `SunFrom` datetime DEFAULT NULL,
  `SunTo` datetime DEFAULT NULL,
  `MonFrom` datetime DEFAULT NULL,
  `MonTo` datetime DEFAULT NULL,
  `TuesFrom` datetime DEFAULT NULL,
  `TuesTo` datetime DEFAULT NULL,
  `WedsFrom` datetime DEFAULT NULL,
  `WedsTo` datetime DEFAULT NULL,
  `ThursFrom` datetime DEFAULT NULL,
  `ThursTo` datetime DEFAULT NULL,
  `FriFrom` datetime DEFAULT NULL,
  `FriTo` datetime DEFAULT NULL,
  `SatFrom` datetime DEFAULT NULL,
  `SatTo` datetime DEFAULT NULL,
  `sun_is_working_hours` tinyint(1) DEFAULT '1',
  `mon_is_working_hours` tinyint(1) DEFAULT '1',
  `tue_is_working_hours` tinyint(1) DEFAULT '1',
  `wed_is_working_hours` tinyint(1) DEFAULT '1',
  `thur_is_working_hours` tinyint(1) DEFAULT '1',
  `fri_is_working_hours` tinyint(1) DEFAULT '1',
  `sat_is_working_hours` tinyint(1) DEFAULT '1',
  `AboutUs` longtext,
  `Testimonials` tinyint(1) DEFAULT '0',
  `Zip_Serv1` varchar(10) DEFAULT NULL,
  `Zip_Serv2` varchar(10) DEFAULT NULL,
  `Zip_Serv3` varchar(10) DEFAULT NULL,
  `Zip_Serv4` varchar(10) DEFAULT NULL,
  `Zip_Serv5` varchar(10) DEFAULT NULL,
  `Zip_Serv6` varchar(10) DEFAULT NULL,
  `Zip_Serv7` varchar(10) DEFAULT NULL,
  `Zip_Serv8` varchar(10) DEFAULT NULL,
  `Zip_Serv9` varchar(10) DEFAULT NULL,
  `Zip_Serv10` varchar(10) DEFAULT NULL,
  `Zip_Serv11` varchar(10) DEFAULT NULL,
  `Zip_Serv12` varchar(10) DEFAULT NULL,
  `Zip_Serv13` varchar(10) DEFAULT NULL,
  `Zip_Serv14` varchar(10) DEFAULT NULL,
  `Zip_Serv15` varchar(10) DEFAULT NULL,
  `Certificate_1` longtext,
  `Certificate_2` longtext,
  `Certificate_3` longtext,
  `Certificate_4` longtext,
  `Certificate_5` longtext,
  `Disclosure` longtext,
  `HasCoupons` tinyint(1) DEFAULT '0',
  `Category1` longtext,
  `Category2` longtext,
  `Category3` longtext,
  `Category4` longtext,
  `Category5` longtext,
  `Facebook` text,
  `Twitter` text,
  `YouTube` text,
  `LinkedIn` text,
  `MySpace` text,
  `GooglePlus` text,
  `Map_Overide` longtext,
  `Title_Overide` longtext,
  `autoTransfer` int DEFAULT '0',
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `usedirections` tinyint(1) DEFAULT '0',
  `noheaderphotos` tinyint(1) DEFAULT '0',
  `phone10` varchar(20) DEFAULT NULL,
  `ezepid` int DEFAULT NULL,
  `ezecategory` varchar(200) DEFAULT NULL,
  `isCancelled` tinyint(1) DEFAULT NULL,
  `DoNotShowPictures` tinyint(1) DEFAULT NULL,
  `DoNotShowVideo` tinyint(1) DEFAULT NULL,
  `DoNotShowAddress` tinyint(1) DEFAULT NULL,
  `DoNotShowMap` tinyint(1) DEFAULT NULL,
  `DoNotShowReviews` tinyint(1) DEFAULT NULL,
  `block_supplemental_results` int DEFAULT NULL,
  `clientMissionStatement` text,
  `wistia` varchar(255) DEFAULT NULL,
  `wistiaXmlFilename` varchar(20) DEFAULT NULL,
  `vimeo` varchar(50) DEFAULT NULL,
  `mspflagset` int DEFAULT NULL,
  `DoNotShowCoupons` tinyint(1) DEFAULT NULL,
  `DoNotShowMenu` tinyint(1) DEFAULT NULL,
  `Instagram` text,
  `citnEmail` varchar(255) DEFAULT NULL,
  `citnEmailPwd` varchar(255) DEFAULT NULL,
  `contactInfoBackgroundImage` varchar(255) DEFAULT NULL,
  `DoNotShowNavigationPhoneNumber` tinyint(1) DEFAULT NULL,
  `OnlineBooking` varchar(255) DEFAULT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `phoneNotification` tinyint(1) DEFAULT '0',
  `emailNotification` tinyint(1) DEFAULT '0',
  `open24per7` tinyint(1) DEFAULT '0',
  `pkg` varchar(50) DEFAULT NULL,
  `setup` decimal(10,2) DEFAULT NULL,
  `installment` decimal(10,2) DEFAULT NULL,
  `installment_period` int DEFAULT '1',
  `installment_period_option` int DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `profile_url` (`URL`),
  UNIQUE KEY `profile_url2` (`URL2`),
  UNIQUE KEY `profile_url3` (`URL3`),
  UNIQUE KEY `profile_url4` (`URL4`),
  UNIQUE KEY `profile_url5` (`URL5`),
  UNIQUE KEY `profile_url6` (`URL6`),
  UNIQUE KEY `profile_contract` (`Contract`),
  UNIQUE KEY `profile_id_cancelled` (`ID`,`isCancelled`),
  KEY `ID` (`ID`),
  KEY `profile_client_id` (`Client_ID`),
  KEY `profile_phone10` (`phone10`),
  KEY `profile_custsince` (`CustomerSince`),
  KEY `idx_profile_businessType` (`BusinessType`)
) ENGINE=MyISAM AUTO_INCREMENT=99999999 DEFAULT CHARSET=utf8mb3;

-- egumball_db.billing_audit definition

CREATE TABLE `billing_audit` (
  `id` varchar(36) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `createdAt` timestamp NULL DEFAULT NULL,
  `payment_amount` varchar(10) DEFAULT NULL,
  `package` varchar(30) DEFAULT NULL,
  `action` varchar(10) DEFAULT NULL,
  `action_timestamp` timestamp NULL DEFAULT NULL,
  `db_user` varchar(100) DEFAULT NULL,
  `demo_user` varchar(100) DEFAULT NULL,
  `payment_method` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;